# Generated by Django 4.2.2 on 2024-02-27 15:47

import django.contrib.auth.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0111_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "This email address is already being used."},
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "This phone number is already being used."},
                max_length=16,
                null=True,
                unique=True,
                validators=[utils.validators.PhoneNumberValidator()],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
